export const PRODUCT_TYPES = {
    SMARTPHONES: "Smartphones",
    TABLETS: "Tablets",
    LAPTOPS: "Laptops",
    HEADPHONES: "Headphones",
    APPLIANCES: "Appliances"
}

export const CATEGORIES = [
    {
        label: PRODUCT_TYPES.SMARTPHONES,
        dataURL: "",
    },
    {
        label: PRODUCT_TYPES.TABLETS,
        dataURL: "",
    },
    {
        label: PRODUCT_TYPES.LAPTOPS,
        dataURL: "",
    },
    {
        label: PRODUCT_TYPES.HEADPHONES,
        dataURL: "",
    },
    {
        label: PRODUCT_TYPES.APPLIANCES,
        dataURL: "",
    }
]

export const DATA = {
    [PRODUCT_TYPES.SMARTPHONES]: {
            'iPhone 11' : {
                Brand: 'Apple',
                OS: "Apple iOS",
                Size: '6,1"',
                Resolution: "828x1792",
                RAM: "4 GB",
                Memory: "64 GB",
                Camera: "12 Mp",
                SIM: "1",
                Cost: 2000,
                Thumb: require("../assets/iphone11.jpeg"),
                Images: [require("../assets/iphone.jpeg"),
                require("../assets/iphone1.jpeg"),
                require("../assets/iphone3.jpeg"),
                require("../assets/iphone6.jpeg"),],
                comments: [],
                favourite: false,
                rating: 0,
                Title: "Smartphone Apple iPhone 11 64GB",
                Description: 'Apple iOS, display 6.1" IPS (828x1792), Apple A13 Bionic, RAM 4 GB, flash-memory 64GB, camera 12 Mp, accumulator 3046 mAh, 1 SIM',

            },
            'iPhone SE' : {
                Brand: 'Apple',
                OS: "Apple iOS",
                Size: '4,7"',
                Resolution: "750x1334",
                RAM: "3 GB",
                Memory: "64 GB",
                Camera: "12 Mp",
                SIM: "1",
                Cost: 1260,
                Thumb: require("../assets/iphonese.jpeg"),
                Images: [require("../assets/iphone.jpeg"),
                require("../assets/iphone1.jpeg"),
                require("../assets/iphone3.jpeg"),
                require("../assets/iphone6.jpeg"),],
                comments: [],
                favourite: false,
                rating: 0,
                Title: "Smartphone Apple iPhone SE 64GB",
                Description: 'Apple iOS, display 4.7" IPS (750x1334), Apple A13 Bionic, RAM 3 GB, flash-memory 64 GB, camera 12 Мp, 1 SIM',

            },
            'iPhone X': {
                Brand: 'Apple',
                OS: "Apple iOS",
                Size: '5,8"',
                Resolution: "1125x2436",
                RAM: "3 GB",
                Memory: "64 GB",
                Camera: "12 Mp",
                SIM: "1",
                Cost: 1900,
                Thumb: require("../assets/iphonex.jpeg"),
                Images: [require("../assets/iphone.jpeg"),
                require("../assets/iphone1.jpeg"),
                require("../assets/iphone3.jpeg"),
                require("../assets/iphone6.jpeg"),],
                comments: [],
                favourite: false,
                rating: 0,
                Title: "Smartphone Apple iPhone X 64GB",
                Description: 'Apple iOS, display 5.8" AMOLED (1125x2436), Apple A11 Bionic, RAM 3 GB, flash-memory 64 GB, camera 12 Мp, accumulator 2716 мАh, 1 SIM',

            },
            'iPhone XR': {
                Brand: 'Apple',
                OS: "Apple iOS",
                Size: '6,1"',
                Resolution: "828x1792",
                RAM: "3 GB",
                Memory: "64 GB",
                Camera: "12 Mp",
                SIM: "1",
                Cost: 1680,
                Thumb: require("../assets/iphonexr.jpeg"),
                Images: [require("../assets/iphone.jpeg"),
                require("../assets/iphone1.jpeg"),
                require("../assets/iphone3.jpeg"),
                require("../assets/iphone6.jpeg"),],
                comments: [],
                favourite: false,
                rating: 0,
                Title: "Smartphone Apple iPhone XR 64GB",
                Description: 'Apple iOS, display 6,1" IPS (828x1792), Apple A12 Bionic, RAM 3 GB, flash-memory 64 GB, camera 12 Мp, accumulator 2942 мАh, 1 SIM',

            },
            'iPhone 8': {
                Brand: 'Apple',
                OS: "Apple iOS",
                Size: '4,7"',
                Resolution: "750x1334",
                RAM: "2 GB",
                Memory: "64 GB",
                Camera: "12 Mp",
                SIM: "1",
                Cost: 1340,
                Thumb: require("../assets/iphone8.jpeg"),
                Images: [require("../assets/iphone.jpeg"),
                require("../assets/iphone1.jpeg"),
                require("../assets/iphone3.jpeg"),
                require("../assets/iphone6.jpeg"),],
                comments: [],
                favourite: false,
                rating: 0,
                Title: "Smartphone Apple iPhone 8 64GB",
                Description: 'Apple iOS, display 4,7" IPS (750x1334), Apple A11 Bionic, RAM 2 GB, flash-memory 64 GB, camera 12 Мp, accumulator 1820 мАh, 1 SIM',

            },
        
            'Samsung S10': {
                Brand: 'Samsung',
                OS: "Android",
                Size: '6,1"',
                Resolution: "1440x3040",
                RAM: "8 GB",
                Memory: "128 GB",
                Camera: "12 Mp",
                SIM: "2",
                Cost: 1790,
                Thumb: require("../assets/s10.jpeg"),
                Images: [require("../assets/iphone.jpeg"),
                require("../assets/iphone1.jpeg"),
                require("../assets/iphone3.jpeg"),
                require("../assets/iphone6.jpeg"),],
                comments: [],
                favourite: false,
                rating: 0,
                Title: "Smartphone Samsung Galaxy S10",
                Description: 'Android, display 6.1" AMOLED (1440x3040), Exynos 9820, RAM 8 GB, flash-memory 128 GB, camera 12 Мp, accumulator 3400 мАh, 2 SIM',

            },
            'Samsung S20': {
                Brand: 'Samsung',
                OS: "Android",
                Size: '6,2"',
                Resolution: "1440x3200",
                RAM: "8 GB",
                Memory: "128 GB",
                Camera: "12 Mp",
                SIM: "2",
                Cost: 1570,
                Thumb: require("../assets/s20.jpeg"),
                Images: [require("../assets/iphone.jpeg"),
                require("../assets/iphone1.jpeg"),
                require("../assets/iphone3.jpeg"),
                require("../assets/iphone6.jpeg"),],
                comments: [],
                favourite: false,
                rating: 0,
                Title: "Smartphone Samsung Galaxy S20",
                Description: 'Android, display 6.2" AMOLED (1440x3200), Exynos 990, RAM 8 GB, flash-memory 128 GB, camera 12 Мp, accumulator 4000 мАh, 2 SIM',

            },
            'Samsung S9': {
                Brand: 'Samsung',
                OS: "Android",
                Size: '5,8"',
                Resolution: "1440x2960",
                RAM: "4 GB",
                Memory: "64 GB",
                Camera: "12 Mp",
                SIM: "2",
                Cost: 1300,
                Thumb: require("../assets/s9.jpeg"),
                Images: [require("../assets/iphone.jpeg"),
                require("../assets/iphone1.jpeg"),
                require("../assets/iphone3.jpeg"),
                require("../assets/iphone6.jpeg"),],
                comments: [],
                favourite: false,
                rating: 0,
                Title: "Smartphone Samsung Galaxy S9 64GB",
                Description: 'Android, display 5,8" AMOLED (1440x2960), Exynos 9810, RAM 4 GB, flash-memory 64 GB, camera 12 Мp, accumulator 3000 мАh, 2 SIM',

            },
            'Samsung S8': {
                Brand: 'Samsung',
                OS: "Android",
                Size: '5,8"',
                Resolution: "1440x2960",
                RAM: "4 GB",
                Memory: "64 GB",
                Camera: "12 Mp",
                SIM: "1",
                Cost: 1150,
                Thumb: require("../assets/s8.jpeg"),
                Images: [require("../assets/iphone.jpeg"),
                require("../assets/iphone1.jpeg"),
                require("../assets/iphone3.jpeg"),
                require("../assets/iphone6.jpeg"),],
                comments: [],
                favourite: false,
                rating: 0,
                Title: "Smartphone Samsung Galaxy S8 64GB",
                Description: 'Android, display 5,8" AMOLED (1440x2960), Exynos 8895, RAM 4 GB, flash-memory 64 GB, camera 12 Мp, accumulator 3000 мАh, 1 SIM',

            },
            'Samsung A51': {
                Brand: 'Samsung',
                OS: "Android",
                Size: '6,5"',
                Resolution: "1080x2400",
                RAM: "4 GB",
                Memory: "64 GB",
                Camera: "48 Mp",
                SIM: "2",
                Cost: 590,
                Thumb: require("../assets/a51.jpeg"),
                Images: [require("../assets/iphone.jpeg"),
                require("../assets/iphone1.jpeg"),
                require("../assets/iphone3.jpeg"),
                require("../assets/iphone6.jpeg"),],
                comments: [],
                favourite: false,
                rating: 0,
                Title: "Smartphone Samsung Galaxy A51 64GB",
                Description: 'Android, display 6,5" AMOLED (1080x2400), Exynos 9611, RAM 4 GB, flash-memory 64 GB, camera 48 Мp, accumulator 4000 мАh, 2 SIM',

            },
    },
    [PRODUCT_TYPES.TABLETS]: {
        'iPhone 11' : {
            Brand: 'Apple',
            OS: "Apple iOS",
            Size: '6,1"',
            Resolution: "828x1792",
            RAM: "4 GB",
            Memory: "64 GB",
            Camera: "12 Mp",
            SIM: "1",
            Cost: 2000,
            comments: [],
            favourite: false,
            rating: 0,
            Title: "Smartphone Apple iPhone 11 64GB",
            Description: 'Apple iOS, display 6.1" IPS (828x1792), Apple A13 Bionic, RAM 4 GB, flash-memory 64GB, camera 12 Mp, accumulator 3046 mAh, 1 SIM',


        },

    },
    [PRODUCT_TYPES.LAPTOPS]: {

    },
    [PRODUCT_TYPES.HEADPHONES]: {

    },
    [PRODUCT_TYPES.APPLIANCES]: {

    }
}

export const USERS = [
    {
        login: 'Admin ',
        password: 'Admin ',
        role: 1,
        name: 'Admin',
        cart: [],
        history: [],
        favourite: []
    },
    {
        login: 'User',
        password: 'User',
        role: 0,
        name: 'User',
        cart: [],
        history: [],
        favourite: []
    },
    {
        login: '',
        password: '',
        role: 0,
        name: 'Temp',
        cart: [],
        history: [],
        favourite: []
    }
]